### ISSUE TITLE
20230121T203606Z.md is a partial VOD

### ISSUE THREAD

**Issue by insanity54** [insanity54/futureporn#119]
I had a **triple** failure of capture instances today.

1) The primary capture VPS ran out of disk space (#95)

2) The backup capture VPS was not running the capture software because it had a dependency missing (dotenv.) Unknown as to why it was missing the dep. Best guess is that I updated the capture software when running playbooks to update the IPFS configuration. I didn't think to check the capture software uptime because I hadn't updated the capture software on purpose. This could have been avoided with better monitoring of capture instances. #97 

3) The backup backup VPS ran out of disk space (#95)

I did not catch the problem until three hours into stream because I was asleep (#106)

Looking for a more complete recording from the community.

**Comment by Linden10** [comment]
I'll try to help! ☆⌒(*＾-゜)v

**Comment by Linden10** [comment]
So I found one video source of the stream that's not cut off, but unfortunately it's not 60fps...

Here's a link to it:
https://www.camwhoresbay.com/videos/653587/projektmelody-2023-01-21-21-59/

You'll need to login to download it but luckily I found an free account on bugmenot so I got it!
Just login with this to download

(I'll edit out this later):
Username: 123aaass
Pass: 123aaass

But I found another video source that's double the filesize of the video above!

Found here:
https://hotwebcams.org/projektmelody-chaturbate-21-01-2023-bigtoys-females/

Though I'm not sure if it's 60fps or not, been trying to download it but the problem is that it's on upstore which requires an premium account to download from! I'm currently looking for ways to get it!

One solution I found is requesting help from someone who has an premium account (might found a way for that.)
The other solution...is to purchase an premium account on upstore to download it and I don't have money to do it...

I'll report my findings on the first solution when I can!

**Comment by insanity54** [comment]
Wow, nice research! 

A couple days ago I got an invite to Fontana's Discord server where ProjektMelody vods are shared. I've been so busy that I haven't looked at what files are shared there until today. I feel bad that I didn't think to mention this earlier, especially given that you put in all the effort to find a better VOD. Today I just found out Fontana has a recording of 20230121T203606Z.

Here's the discord server if you're interested -> https://discord.com/invite/fdPTFA6Bx5

Anyway, do you mind if I put your name in the VOD contributions section on Futureporn? I appreciate that you found copies of the vod. Even if we couldn't find a 60fps copy, a longer video is better than the one I recorded and I think incremental improvements are important.

**Comment by Linden10** [comment]
Ah you might not know but it’s me Jake Well! I’m already on your contributions haha, happy to help!

Nice to know there’s a discord server with her vods, hopefully the vod on there is High Quality!

I posted on a forum requesting to download the upstore link, maybe it’s not needed but I’ll be checking it out!

**Comment by insanity54** [comment]
Oh ok! It's Jake Well haha, a familiar name. Thanks again! Yeah you never know, upstore access might come in handy someday.

**Comment by Linden10** [comment]
Oh my gosh I just got an even higher quality version of the vod and it's 60fps too!
I got it from a fellow Science Team member on that forum, they kindly linked me to an 10GB vod of the stream!

Only caveat is it doesn't have the beginning of the vod (It's like the ones I posted above) but it should probably be possible for you to combine your vod with this vod to make it complete and 60fps...maybe!

Here's a link to the vod!
https://mega.nz/file/id9RiLJT#_SE_qzAjTSJrXE0Mi1H1iDtMGAeGuErXCTLP0LT6KkU

**Comment by insanity54** [comment]
Ooo, good work! Yeah that does look good quality. I don't think it's the whole stream though. Fontana's server has a vod for this date with duration 04:18:40. https://drive.google.com/file/d/11HEgO6m1DTCCWQWtDmiTzFD8XSp05Y1l/view 

The mega file you linked has duration 03:41:54. I think I'll look into your suggestion to concat the two files.

**Comment by Linden10** [comment]
Ah I was sort of right that they’re incomplete…I should've throughly checked the vods more.

Well if you can concat them then it should fix the problem. 🙂

**Comment by insanity54** [comment]
marking this as complete
